server:
  port: 8888

application:
  name: api-gateway
  description: API Gateway for microservices
  version: 1.0.0

app:
  api-prefix: /api

services-host:
  identity-service: ${IDENTITY_SERVICE_URI:http://localhost:8081}
  profile-service: ${PROFILE_SERVICE_URI:http://localhost:8082}
  notification-service: ${NOTIFICATION_SERVICE_URI:http://localhost:8083}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: ${services-host.identity-service}
          predicates:
            - Path=${app.api-prefix}/identity/** # api prefix to reference the variable be defined in the app section
          filters:
            - StripPrefix=1 # =1 will replace one / in path (/api) | =2 will replace two / in path (/api/identity)
        - id: profile-service
          uri: ${services-host.profile-service}
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: ${services-host.notification-service}
          predicates:
            - Path=${app.api-prefix}/notification/** 
          filters:
            - StripPrefix=1